#!/bin/sh 
# /etc/init.d

### BEGIN INIT INFO
# Provides:          autolaunchskeleton
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: autostart initscript
# Description:       
### END INIT INFO

sleep 5   # make sure boot process is done, no more console msgs
echo "AAA"
. /etc/profile
echo $PATH
sudo pigpiod


exit 0
